tp_python/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tp_python_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

tp_python_app/urls.py
from django.urls import path
from . import views

app_name = 'tp_python_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('empleados/<str:dni>', views.un_empleado, name='un_empleado'),
    path('empleados', views.lista_empleados, name='lista_empleados'),
    path('buscar-empleado', views.buscar_empleado, name='buscar_empleado'),
    path('crear-empleado', views.crear_empleado, name='crear_empleado'),
    path('editar-empleado/<str:dni>', views.editar_empleado, name='editar_empleado'),
    path('guardar-empleado', views.guardar_empleado, name='guardar_empleado'),
    path('guardar-empleado-editado', views.guardar_empleado_editado, name="guardar_empleado_editado"),
    path('borrar-empleado/<str:dni>', views.borrar_empleado, name="borrar_empleado"),
]

tp_python_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class Empleado(models.Model):
    dni = models.CharField(max_length=8, primary_key=True)
    usuario = models.ForeignKey(User, models.RESTRICT, blank=True, null=True)
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    fecha_de_nacimiento = models.DateField(null=True, blank=False)
    
    class Sexo(models.TextChoices):
        FEMENINO = 'F', _('Femenino')
        MASCULINO = 'M', _('Masculino')
        OTRO = 'O', _('Otro')
        
    sexo = models.CharField(
        max_length=1,
        choices=Sexo.choices,
    )
        
    class EstadoCivil(models.TextChoices):
        SOLTERO = 'S', _('Soltero')    
        CASADO = 'C', _('Casado')
        DIVORCIADO = 'D', _('Divorciado')
        VIUDO = 'V', _('Viudo')
    
    estado_civil = models.CharField(
        max_length=1,
        choices=EstadoCivil.choices,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

tp_python_app/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from . models import Empleado

class EmpleadoForm(forms.Form):
    dni = forms.CharField(label='Ingrese DNI', max_length=8)

class EmpleadoEditarForm(ModelForm):
    class Meta:
        model = Empleado
        fields = ['dni', 'nombre', 'apellido', 'fecha_de_nacimiento', 'sexo', 'estado_civil']
        widgets = {
            'fecha_de_nacimiento': forms.DateInput(attrs={'type': 'date'})
        }
        
    username = forms.CharField(required=True, max_length=30)
    password = forms.CharField(required=True, max_length=128)
    email = forms.EmailField(required=True)

tp_python_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import Empleado
from django.contrib.auth.models import User
from . forms import EmpleadoForm, EmpleadoEditarForm
from django.http import HttpResponseNotFound

def index (request):
    return render(request, "index.html")

def un_empleado (request, dni):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
    
    try: 
        empleado = Empleado.objects.get(dni=dni)
    except Empleado.DoesNotExist:
        return HttpResponseNotFound('El empleado no existe. Por favor presione Atrás en su navegador.')
    
    context = {'empleado': empleado}
    
    return render(request, "un_empleado.html", context)

def lista_empleados (request):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
        
    empleados = Empleado.objects.all()
    context = {'empleados': empleados}
    
    return render(request, "lista_empleados.html", context)

def buscar_empleado (request):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
    
    if request.method == 'POST':
        return redirect('/empleados/' + request.POST.get('dni'))
    
    empleadoForm = EmpleadoForm()
    context = {'empleado_form': empleadoForm}
    
    return render(request, "buscar_empleado.html", context)

def crear_empleado (request):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
    
    empleadoEditarForm = EmpleadoEditarForm()
    context = {'empleado_editar_form': empleadoEditarForm}
    
    return render(request, "editar_empleado.html", context)

def editar_empleado (request, dni):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
    
    try: 
        empleado = Empleado.objects.get(dni=dni)
    except Empleado.DoesNotExist:
        return HttpResponseNotFound('El empleado no existe. Por favor presione Atrás en su navegador.')
    
    empleadoEditarForm = EmpleadoEditarForm(instance=empleado)
    empleadoEditarForm.fields['dni'].widget.attrs['readonly'] = True
    empleadoEditarForm.fields['password'].widget.attrs['readonly'] = True
    
    empleadoEditarForm.initial['username'] = empleado.usuario.username
    empleadoEditarForm.initial['password'] = empleado.usuario.password
    empleadoEditarForm.initial['email'] = empleado.usuario.email
    
    context = {
        'empleado_editar_form': empleadoEditarForm,
        'editando': True
    }
    
    return render(request, "editar_empleado.html", context)

def guardar_empleado (request):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
    
    nuevo_empleado_form = EmpleadoEditarForm(request.POST)
    empleado_creado = nuevo_empleado_form.save(commit=False)
    
    nuevo_usuario = User.objects.create_user(
        username = request.POST.get('username'),
        password = request.POST.get('password'),
        email = request.POST.get('email'),
        first_name = request.POST.get('nombre'),
        last_name = request.POST.get('apellido')
    )
    
    empleado_creado.usuario = nuevo_usuario
    empleado_creado.save()
    
    return redirect('/empleados')

def guardar_empleado_editado (request):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
    
    try: 
        empleado = Empleado.objects.get(dni=request.POST.get('dni'))
    except Empleado.DoesNotExist:
        return HttpResponseNotFound('El empleado no existe. Por favor presione Atrás en su navegador.')
    
    empleado_editado_form = EmpleadoEditarForm(request.POST, instance=empleado)
        
    if empleado_editado_form.is_valid():
        empleado_guardado = empleado_editado_form.save()
    else: 
        return HttpResponseNotFound('Error al editar al empleado.')
        
    empleado_guardado.usuario.username = request.POST.get('username')
    empleado_guardado.usuario.email = request.POST.get('email')
    empleado_guardado.usuario.first_name = request.POST.get('nombre')
    empleado_guardado.usuario.last_name = request.POST.get('apellido')
    
    empleado_guardado.usuario.save()
        
    return redirect('/empleados')

def borrar_empleado (request, dni):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('No tiene autorización para ver esta página. Por favor, ingrese al sistema.')
    
    try: 
        empleado_borrar = Empleado.objects.get(dni=dni)
    except Empleado.DoesNotExist:
        return HttpResponseNotFound('El empleado no existe. Por favor presione Atrás en su navegador.')
    
    usuario = empleado_borrar.usuario
    
    empleado_borrar.delete()
    usuario.delete()
 
    return redirect('/empleados')

tp_python_app/templates/buscar_empleado.html
{% extends 'index.html' %}
{% load django_bootstrap5 %}

{% block body %}

<form action="" method="post" class="form">
    {% csrf_token %}

    {% bootstrap_form empleado_form %}

    {% bootstrap_button button_type="submit" content="Buscar" %}
</form>

{% endblock body %}

tp_python_app/templates/editar_empleado.html
{% extends 'index.html' %}
{% load django_bootstrap5 %}

{% block body %}

<form action="{% if editando == True %} {% url 'tp_python_app:guardar_empleado_editado' %}{% else %} {% url 'tp_python_app:guardar_empleado' %} {% endif %}" method="post" class="form">
    {% csrf_token %}

    {% bootstrap_form empleado_editar_form %}

    {% bootstrap_button button_type="submit" content="Guardar" %}

    <a href="{% url 'tp_python_app:lista_empleados' %}" >
        <button type="button" class="btn btn-danger">Cancelar</button>
    </a>
</form>

{% endblock body %}

tp_python_app/templates/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>Gestión de empleados</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/estilos.css' %}" rel="stylesheet" />

        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% bootstrap_messages %}

    </head>
    <body>
        <header>
            <div class="content container d-none d-sm-block" style="text-align: center">
                <div class="row">
                    <div>
                        <div style="margin-top: 20px">
                            <h1>Gestión de empleados</h1>
                        </div>
                    </div>
                </div>
            </div>    
            <nav class="navbar navbar-expand-sm navbar-light navbar-default bg-body">
                <div class="container-fluid">
                    <a class="navbar-bar menu d-sm-none" style="text-decoration: none; color: #5251aa; font-size: 24px; margin: auto" href="#">Gestión de empleados</a>
                    <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                        <div class="collapse navbar-collapse justify-content-center" id="navbar">
                            <ul class="nav navbar-nav justify-content-center nav-pills" style="margin-top: 50px">
                                <li class="nav-item" >
                                    <a href="{% url 'tp_python_app:index' %}" class="nav-link active" style="background-color: rgb(250, 228, 232);">Inicio</a>
                                </li>
                                {% if request.user.is_authenticated %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'tp_python_app:lista_empleados' %}">Listado</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'tp_python_app:crear_empleado' %}">Crear</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'tp_python_app:buscar_empleado' %}">Buscar</a>
                                </li>
                                {% endif %}
                                {% if request.user.is_superuser %}
                                <li> 
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                                </li>
                                {% endif %}
                                {% if request.user.is_authenticated %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'logout' %}?next=/">Logout</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            {% block body %}
            <div>
                {% if not request.user.is_authenticated %}
                <div class="content container" style="text-align: center">
                    <div class="row">
                        <div style="margin-top: 100px">
                            <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="content container" style="text-align: center">
                    <div class="row">
                        <div style="margin-top: 100px">
                            <h4>Bienvenido al sistema. Elija una opción del menú superior.</h4>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
            {% endblock %}
        </main>
        <footer>
        
        </footer>
        
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

tp_python_app/templates/lista_empleados.html
{% extends 'index.html' %}
{% load static %}
<link href="{% static 'css/styles.css' %}" rel="stylesheet" />

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="table-responsive-lg">
            <table class="table table-striped table-bordered caption-top" border="1" table-layout="fixed" cellpadding="8" border-collapse="collapse" style="margin-top: 30px">
                <caption style="text-align: center">Datos de todos los empleados</caption>
                <thead>
                    <tr class="align-middle">
                        <th scope="col">DNI</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">Sexo</th>
                        <th scope="col">Email</th>
                        <th scope="col">Fecha de nacimiento</th>
                        <th scope="col">Estado civil</th>
                        <th scope="col">Editar</th>
                        <th scope="col">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                        <tr class="align-middle">
                            <th scope="row">{{ empleado.dni }}</th>
                            <th scope="row">{{ empleado.nombre }}</th>
                            <th scope="row">{{ empleado.apellido }}</th>
                            <th scope="row">{{ empleado.sexo }}</th>
                            <th scope="row">{{ empleado.usuario.email }}</th>
                            <th scope="row">{{ empleado.fecha_de_nacimiento | date:'Y-m-d' }}</th>
                            <th scope="row">{{ empleado.estado_civil }}</th>
                            <th scope="row">
                                <a href="{% url 'tp_python_app:editar_empleado' dni=empleado.dni %}" >
                                    <button type="button" class="btn btn-warning btn-rounded btn-sm px-3">
                                        <i class="fas fa-magic"></i>
                                    </button>
                                </a>
                            </th>
                            <th scope="row">
                                <a href="{% url 'tp_python_app:borrar_empleado' dni=empleado.dni %}" >
                                    <button type="button" class="btn btn-danger btn-rounded btn-sm px-3">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </a>
                            </th>
                        </tr>
                    {% empty %}
                        <tr>
                            <th colspan="9" style="text-align: center">
                                <h3>No hay registros de empleados para mostrar</h3>
                            </th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>   
</div>

{% endblock %}

tp_python_app/templates/un_empleado.html
{% extends 'index.html' %}

{% block body %}

<h4>
    Datos del empleado:
</h4>
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-4 col-md-4 col-sm-12">
            DNI: {{ empleado.dni }} <br />
            Nombre: {{ empleado.nombre }} <br />
            Apellido: {{ empleado.apellido }} <br />
            Fecha de nacimiento: {{ empleado.fecha_de_nacimiento | date:'Y-m-d' }} <br />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-6">
            <div style="margin-top: 40px">
                <a href="{% url 'tp_python_app:editar_empleado' dni=empleado.dni %}" >
                    <button type="button" class="btn btn-warning btn-rounded btn-sm px-3">
                        <i class="fas fa-magic"></i>
                    </button>
                </a>
            </div>
        </div>
        <div class="col-md-2 col-6">
            <div style="margin-top: 40px">
                <a href="{% url 'tp_python_app:borrar_empleado' dni=empleado.dni %}" >
                    <button type="button" class="btn btn-danger btn-rounded btn-sm px-3">
                        <i class="fas fa-times"></i>
                    </button>
                </a>
            </div>
        </div>    
    </div>
</div>

{% endblock %}